from __future__ import annotations

from dataclasses import dataclass
import re
from typing import Any

from src.context.documents import tokenize
from src.semantic.loader import DEFAULT_SEMANTIC_LAYER_PATH, load_semantic_layer_cached
from src.semantic.models import (
    CanonicalFilter,
    SemanticDimension,
    SemanticLayerDefinition,
    SemanticMetric,
)
from src.semantic.validation import shortest_join_path


@dataclass(frozen=True)
class SemanticCompileResult:
    matched: bool
    sql: str = ""
    explanation: str = ""
    metric_id: str | None = None
    metric_version: str | None = None
    dimensions: tuple[str, ...] = ()
    filters: tuple[str, ...] = ()
    joins: tuple[str, ...] = ()
    owner: str | None = None
    sensitivity: str | None = None
    confidence: float = 0.0
    reason: str = ""
    unsupported: bool = False
    disclosure: dict[str, Any] | None = None


class SemanticLayer:
    def __init__(self, definition: SemanticLayerDefinition) -> None:
        self.definition = definition
        self.metrics = {item.id: item for item in definition.metrics}
        self.dimensions = {item.id: item for item in definition.dimensions}
        self.filters = {item.id: item for item in definition.filters}

    @classmethod
    def from_default(cls) -> "SemanticLayer":
        return cls(load_semantic_layer_cached(str(DEFAULT_SEMANTIC_LAYER_PATH)))

    @classmethod
    def from_path(cls, path: str) -> "SemanticLayer":
        return cls(load_semantic_layer_cached(path))

    def compile_question(self, question: str, schema: dict[str, Any]) -> SemanticCompileResult:
        q_tokens = set(tokenize(question))
        metric, metric_score = self._best_metric(question, q_tokens)
        if metric is None or metric_score < 0.75:
            return SemanticCompileResult(matched=False, reason="no_semantic_metric_match")
        if not self._schema_supports_tables(schema, [metric.source]):
            return SemanticCompileResult(matched=False, reason="semantic_metric_not_supported_by_schema")

        has_grouping_intent = bool(
            re.search(r"\bby\b|\bper\b|\bgroup(ed)?\b", question, flags=re.IGNORECASE)
        )
        requested_dimensions = self._requested_dimensions(question, q_tokens, metric)
        requested_filters = self._requested_filters(question, q_tokens, metric)
        if not has_grouping_intent:
            return SemanticCompileResult(matched=False, reason="semantic_metric_requires_explicit_grouping")
        if has_grouping_intent and not requested_dimensions:
            return SemanticCompileResult(matched=False, reason="no_semantic_dimension_match")
        unsupported_dimensions = [
            dimension.id
            for dimension in requested_dimensions
            if dimension.id not in metric.allowed_dimensions
        ]
        unsupported_filters = [
            filter_def.id for filter_def in requested_filters if filter_def.id not in metric.allowed_filters
        ]
        if unsupported_dimensions or unsupported_filters:
            reason = (
                f"Semantic metric {metric.id} does not allow requested "
                f"dimensions={unsupported_dimensions or []} filters={unsupported_filters or []}."
            )
            return SemanticCompileResult(
                matched=True,
                metric_id=metric.id,
                metric_version=metric.version,
                unsupported=True,
                reason=reason,
                confidence=min(0.99, metric_score),
                disclosure=self._disclosure(metric, [], [], [], reason=reason),
            )
        requested_tables = [dimension.table for dimension in requested_dimensions]
        requested_tables.extend(filter_def.table for filter_def in requested_filters)
        if not self._schema_supports_tables(schema, [metric.source, *requested_tables]):
            return SemanticCompileResult(matched=False, reason="semantic_metric_not_supported_by_schema")

        sql, joins = self._compile_sql(metric, requested_dimensions, requested_filters)
        reason = f"Semantic metric {metric.id} compiled deterministically."
        return SemanticCompileResult(
            matched=True,
            sql=sql,
            explanation=(
                f"Compiled from semantic metric {metric.id} v{metric.version}; "
                "no arbitrary metric expression was generated by the provider."
            ),
            metric_id=metric.id,
            metric_version=metric.version,
            dimensions=tuple(dimension.id for dimension in requested_dimensions),
            filters=tuple(filter_def.id for filter_def in requested_filters),
            joins=tuple(join.id for join in joins),
            owner=metric.owner,
            sensitivity=metric.sensitivity,
            confidence=min(0.99, max(0.75, metric_score)),
            reason=reason,
            disclosure=self._disclosure(metric, requested_dimensions, requested_filters, joins, reason=reason),
        )

    def _best_metric(self, question: str, q_tokens: set[str]) -> tuple[SemanticMetric | None, float]:
        scored = [(metric, self._score(question, q_tokens, [metric.id, *metric.synonyms])) for metric in self.definition.metrics]
        scored.sort(key=lambda item: (-item[1], item[0].id))
        return scored[0] if scored and scored[0][1] > 0 else (None, 0.0)

    def _requested_dimensions(
        self, question: str, q_tokens: set[str], metric: SemanticMetric
    ) -> list[SemanticDimension]:
        if not re.search(r"\bby\b|\bper\b|\bgroup(ed)?\b", question, flags=re.IGNORECASE):
            return []
        grouping_text = self._grouping_text(question)
        grouping_tokens = set(tokenize(grouping_text))
        dimensions = []
        q_lower = grouping_text.lower()
        for dimension in self.definition.dimensions:
            if not self._dimension_requested(grouping_text, grouping_tokens, dimension):
                continue
            if dimension.id in metric.allowed_dimensions:
                dimensions.append(dimension)
                continue
            exact_phrases = [dimension.id.replace("_", " "), dimension.label.lower()]
            exact_phrases.extend(synonym.lower() for synonym in dimension.synonyms if " " in synonym)
            if any(phrase and phrase in q_lower for phrase in exact_phrases):
                dimensions.append(dimension)
        dimensions.sort(key=lambda item: item.id)
        return dimensions

    def _grouping_text(self, question: str) -> str:
        match = re.search(r"\b(?:by|per|group(?:ed)? by)\b(.+)$", question, flags=re.IGNORECASE)
        return match.group(1).strip() if match else question

    def _requested_filters(
        self, question: str, q_tokens: set[str], metric: SemanticMetric
    ) -> list[CanonicalFilter]:
        filters = [
            filter_def
            for filter_def in self.definition.filters
            if self._score(question, q_tokens, [filter_def.id, filter_def.label, *filter_def.synonyms]) > 0
        ]
        if not filters and metric.id == "paid_invoice_value" and "paid_invoices" in metric.allowed_filters:
            filters = [self.filters["paid_invoices"]]
        filters.sort(key=lambda item: item.id)
        return filters

    def _dimension_requested(
        self, grouping_text: str, grouping_tokens: set[str], dimension: SemanticDimension
    ) -> bool:
        q_lower = grouping_text.lower()
        for phrase in [dimension.id, dimension.label, *dimension.synonyms]:
            normalized = phrase.replace("_", " ").lower().strip()
            if not normalized:
                continue
            if normalized in q_lower:
                return True
            phrase_tokens = set(tokenize(normalized))
            if phrase_tokens and phrase_tokens.issubset(grouping_tokens):
                return True
        return False

    def _score(self, question: str, q_tokens: set[str], phrases: list[str]) -> float:
        q_lower = question.lower()
        score = 0.0
        for phrase in phrases:
            normalized = phrase.replace("_", " ").lower().strip()
            if not normalized:
                continue
            if normalized in q_lower:
                score = max(score, 1.0 if " " in normalized else 0.85)
            tokens = set(tokenize(normalized))
            if tokens:
                score = max(score, len(tokens.intersection(q_tokens)) / len(tokens))
        return round(score, 3)

    def _schema_supports_tables(self, schema: dict[str, Any], tables: list[str]) -> bool:
        schema_tables = {str(table.get("table", "")) for table in schema.get("tables", [])}
        if not schema_tables:
            return False
        return set(tables).issubset(schema_tables)

    def _compile_sql(
        self,
        metric: SemanticMetric,
        dimensions: list[SemanticDimension],
        filters: list[CanonicalFilter],
    ):
        joins = []
        selected = [
            f"{dimension.expression} AS {dimension.id}" for dimension in dimensions
        ]
        selected.append(f"{metric.expression} AS {metric.id}")
        tables_needed = [dimension.table for dimension in dimensions] + [filter_def.table for filter_def in filters]
        for table in tables_needed:
            for join in shortest_join_path(self.definition, metric.source, table):
                if join.id not in {item.id for item in joins}:
                    joins.append(join)
        clauses = [f"SELECT {', '.join(selected)}", f"FROM {metric.source}"]
        for join in joins:
            clauses.append(
                f"JOIN {join.right_table} ON {join.left_table}.{join.left_column} = "
                f"{join.right_table}.{join.right_column}"
            )
        if filters:
            clauses.append("WHERE " + " AND ".join(filter_def.expression for filter_def in filters))
        if dimensions:
            clauses.append("GROUP BY " + ", ".join(dimension.expression for dimension in dimensions))
            clauses.append("ORDER BY " + ", ".join(dimension.expression for dimension in dimensions))
        return " ".join(clauses), joins

    def _disclosure(
        self,
        metric: SemanticMetric,
        dimensions: list[SemanticDimension],
        filters: list[CanonicalFilter],
        joins: list,
        *,
        reason: str,
    ) -> dict[str, Any]:
        return {
            "semantic_layer_id": self.definition.id,
            "semantic_layer_version": self.definition.version,
            "metric": {
                "id": metric.id,
                "version": metric.version,
                "description": metric.description,
                "expression": metric.expression,
                "owner": metric.owner,
                "sensitivity": metric.sensitivity,
            },
            "dimensions": [
                {
                    "id": dimension.id,
                    "label": dimension.label,
                    "expression": dimension.expression,
                    "sensitivity": dimension.sensitivity,
                }
                for dimension in dimensions
            ],
            "filters": [
                {"id": filter_def.id, "label": filter_def.label, "expression": filter_def.expression}
                for filter_def in filters
            ],
            "joins": [
                {
                    "id": join.id,
                    "left": f"{join.left_table}.{join.left_column}",
                    "right": f"{join.right_table}.{join.right_column}",
                    "relationship": join.relationship,
                }
                for join in joins
            ],
            "reason": reason,
        }
